services:
  server:
    build:
      context: ./Back
      dockerfile: ./Dockerfile
    container_name: chat-server
    ports:
      - "5000:5000"

    depends_on:
      - mongodb

  client:
    build:
      context: ./Front
      dockerfile: ./Dockerfile

    container_name: chat-client
    ports:
      - "5173:5173"
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    ports:
      - "27017:27017"

    volumes:
      - ./../mydata:/data/db

# Volumes define
volumes:
  mydata:
